### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by sarthak501** [diezo/ProGPT#7]
File "/home/runner/sarthakgpt/main.py", line 6, in <module>
    print(bot.prompt("who invented electricity?"))
  File "/home/runner/sarthakgpt/.pythonlibs/lib/python3.10/site-packages/ProGPT/Generative.py", line 84, in prompt
    if data["message"]["status"] != "finished_successfully":
KeyError: 'message'
Traceback (most recent call last):
  File "/home/runner/sarthakgpt/main.py", line 6, in <module>
    print(bot.prompt("who invented electricity?"))
  File "/home/runner/sarthakgpt/.pythonlibs/lib/python3.10/site-packages/ProGPT/Generative.py", line 84, in prompt
    if data["message"]["status"] != "finished_successfully":
KeyError: 'message'

**Comment by diezo** [comment]
@sarthak501 I've figured out the cause of this issue and will implement a solution very soon.
In the meantime, please do give this repository a star so that other developers can know about ProGPT as well. Thanks

**Comment by justin321123** [comment]
@sarthak501 #5, issue is being solved soonly. No need to open a new one ;)

**Comment by sarthak501** [comment]
its been 2 weeks still not working

**Comment by cycyrild** [comment]
Same error for me

**Comment by smb-sh** [comment]
i have the same error
